# Generated by Django 2.1.7 on 2019-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_feature_varient_featuremaster_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.IntegerField(default=True)),
                ('mrp', models.FloatField(default=True)),
                ('discount', models.FloatField(default=True)),
            ],
        ),
    ]
