# Generated by Django 2.1.7 on 2019-04-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_models',
            name='idname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Brand'),
            preserve_default=False,
        ),
    ]
