# Generated by Django 2.1.7 on 2019-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_product_models_idname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_models',
            name='model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
