# Generated by Django 2.1.7 on 2019-04-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190411_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='variant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Items'),
            preserve_default=False,
        ),
    ]
